@baseUrl = http://localhost:5000
##################################################


################################################## customers
DELETE {{baseUrl}}/customers/1
#####
GET {{baseUrl}}/customers
#####
GET {{baseUrl}}/customers/1
#####
POST {{baseUrl}}/customers
Content-type: application/json

{
   "id": 1,
   "personName": "abc",
   "companyName": "abc",
   "mailAdress": "abc",
   "phoneNumber": "abc",
   "city": "abc",
   "street": "abc",
   "zipCode": 1,
   "country": "abc",
   "discount": 1,
   "paymentTerms": "abc"
}
#####
PUT {{baseUrl}}/customers/1
Content-type: application/json

{
   "id": 1,
   "personName": "abc",
   "companyName": "abc",
   "mailAdress": "abc",
   "phoneNumber": "abc",
   "city": "abc",
   "street": "abc",
   "zipCode": 1,
   "country": "abc",
   "discount": 1,
   "paymentTerms": "abc"
}
#####

################################################## orders
DELETE {{baseUrl}}/orders/1
#####
GET {{baseUrl}}/orders
#####
GET {{baseUrl}}/orders/1
#####
POST {{baseUrl}}/orders
Content-type: application/json

{
   "id": 1,
   "customerId": 1,
   "paperId": 1,
   "printerId": 1,
   "productName": "abc",
   "title": "abc",
   "binding": 1,
   "formatL": 1,
   "formatB": 1,
   "endFormatL": 1,
   "endFormatB": 1,
   "pages": 1,
   "gap": 1,
   "nutzen": 1,
   "nutzenM": 1,
   "trimming": "abc",
   "shippingCost": 1,
   "paperPages": 1,
   "schoen": 1,
   "wider": 1,
   "materialName": "abc",
   "batch1": 1,
   "batchInformation1": "abc",
   "priceManuell1": 1,
   "price1": 1,
   "batch2": 1,
   "batchInformation2": "abc",
   "priceManuell2": 1,
   "price2": 1,
   "batch3": 1,
   "batchInformation3": "abc",
   "priceManuell3": 1,
   "price3": 1,
   "discount": 1,
   "date": "abc"
}
#####
PUT {{baseUrl}}/orders/1
Content-type: application/json

{
   "id": 1,
   "customerId": 1,
   "paperId": 1,
   "printerId": 1,
   "productName": "abc",
   "title": "abc",
   "binding": 1,
   "formatL": 1,
   "formatB": 1,
   "endFormatL": 1,
   "endFormatB": 1,
   "pages": 1,
   "gap": 1,
   "nutzen": 1,
   "nutzenM": 1,
   "trimming": "abc",
   "shippingCost": 1,
   "paperPages": 1,
   "schoen": 1,
   "wider": 1,
   "materialName": "abc",
   "batch1": 1,
   "batchInformation1": "abc",
   "priceManuell1": 1,
   "price1": 1,
   "batch2": 1,
   "batchInformation2": "abc",
   "priceManuell2": 1,
   "price2": 1,
   "batch3": 1,
   "batchInformation3": "abc",
   "priceManuell3": 1,
   "price3": 1,
   "discount": 1,
   "date": "abc"
}
#####

################################################## products
DELETE {{baseUrl}}/products/papers/1
#####
DELETE {{baseUrl}}/products/postprocessings/1
#####
DELETE {{baseUrl}}/products/printers/1
#####
GET {{baseUrl}}/products/papers
#####
GET {{baseUrl}}/products/papers/1
#####
GET {{baseUrl}}/products/postprocessings/1
#####
GET {{baseUrl}}/products/printers
#####
GET {{baseUrl}}/products/printers/1
#####
POST {{baseUrl}}/products/papers
Content-type: application/json

{
   "id": 1,
   "name": "abc",
   "buyPrice": 1,
   "sellPrice": 1,
   "brand": "abc",
   "formatWidth": 1,
   "formatLength": 1,
   "grammatur": 1,
   "volume": 1,
   "amount": 1,
   "pricePerKg": 1,
   "kg": 1,
   "calcPricePerKg": 1,
   "stapelHöheMM": 1,
   "bogen": 1
}
#####
POST {{baseUrl}}/products/postprocessings
Content-type: application/json

{
   "id": 1,
   "printerId": 1,
   "bindingType": "abc",
   "standardPaperName": "abc",
   "cuttingTime": 1,
   "cuttingCostEur": 1,
   "cuttingStackHeight": 1,
   "cuttingLarge": 1,
   "cuttingSmall": 1,
   "cuttingMaxSmallFormat": 1,
   "cuttingCutContour": 1,
   "numberCircleOffer": 1,
   "numberCircleCalculation": 1,
   "numberCircleOrder": 1,
   "numberCircleService": 1,
   "activeUser": "abc",
   "activeUserRole": "abc",
   "activeUserId": "abc",
   "programmingNote": "abc",
   "cartonLabels": "abc",
   "labelPrinterIpAddress": "abc"
}
#####
POST {{baseUrl}}/products/printers
Content-type: application/json

{
   "id": 1,
   "name": "abc",
   "unprintedEdgeMM": 1,
   "formatName": "abc",
   "buyPrinceFor4cKlick": 1,
   "buyPrinceFor1cKlick": 1,
   "sellPriceFor4cKlick": 1,
   "sellPriceFor1cKlick": 1,
   "formatWidth": 1,
   "formatLength": 1,
   "inactive": 1
}
#####
PUT {{baseUrl}}/products/papers/1
Content-type: application/json

{
   "id": 1,
   "name": "abc",
   "buyPrice": 1,
   "sellPrice": 1,
   "brand": "abc",
   "formatWidth": 1,
   "formatLength": 1,
   "grammatur": 1,
   "volume": 1,
   "amount": 1,
   "pricePerKg": 1,
   "kg": 1,
   "calcPricePerKg": 1,
   "stapelHöheMM": 1,
   "bogen": 1
}
#####
PUT {{baseUrl}}/products/postprocessings/1
Content-type: application/json

{
   "id": 1,
   "printerId": 1,
   "bindingType": "abc",
   "standardPaperName": "abc",
   "cuttingTime": 1,
   "cuttingCostEur": 1,
   "cuttingStackHeight": 1,
   "cuttingLarge": 1,
   "cuttingSmall": 1,
   "cuttingMaxSmallFormat": 1,
   "cuttingCutContour": 1,
   "numberCircleOffer": 1,
   "numberCircleCalculation": 1,
   "numberCircleOrder": 1,
   "numberCircleService": 1,
   "activeUser": "abc",
   "activeUserRole": "abc",
   "activeUserId": "abc",
   "programmingNote": "abc",
   "cartonLabels": "abc",
   "labelPrinterIpAddress": "abc"
}
#####
PUT {{baseUrl}}/products/printers/1
Content-type: application/json

{
   "id": 1,
   "name": "abc",
   "unprintedEdgeMM": 1,
   "formatName": "abc",
   "buyPrinceFor4cKlick": 1,
   "buyPrinceFor1cKlick": 1,
   "sellPriceFor4cKlick": 1,
   "sellPriceFor1cKlick": 1,
   "formatWidth": 1,
   "formatLength": 1,
   "inactive": 1
}
#####
PUT {{baseUrl}}/products/printers/changeInactive/1
#####

################################################## users
DELETE {{baseUrl}}/users/1
#####
GET {{baseUrl}}/users
#####
GET {{baseUrl}}/users/1
#####
POST {{baseUrl}}/users
Content-type: application/json

{
   "id": 1,
   "name": "abc",
   "password": "abc",
   "role": "abc"
}
#####
PUT {{baseUrl}}/users/1
Content-type: application/json

{
   "id": 1,
   "name": "abc",
   "password": "abc",
   "role": "abc"
}
#####
